### ISSUE TITLE
Add Encryption

### ISSUE THREAD

**Issue by firesalp** [jobec/powershell-prom-client#11]
Hello @jobec,

You did a nice job here! 

We are looking to implement this exporter in our infrastructure, but our security standards are asking for encryption in the HTTP response. Like Windows_Exporter, is there a way to add a web certificate and a user in a web-config.yaml?

```
tls_server_config:
  cert_file: "Windows_Exporter.crt"
  key_file: "Windows_Exporter.key"
basic_auth_users:
  prometheus: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
